### ISSUE TITLE
Read flags from a global file

### ISSUE THREAD

**Issue by ghost** [foutrelis/chromium-launcher#3]
It might be helpful to be able to read flags from both the user's `~/.config/chromium-flags.conf` and a global file, possibly `/etc/chromium-flags.conf`.

**Comment by foutrelis** [comment]
A single file would be too limiting and a configuration directory would be too complicated and possibly an overkill. For single-user machines, the existing implementation suffices. For systems with many users, it's not clear that a global configuration would be appropriate for all of them.

Thank you for taking the time to suggest this, but the use case for a global file isn't interesting to me.

**Comment by ghost** [comment]
Thanks for the response! I guess I will implement this in my own fork then.

**Comment by nhandt64** [comment]
Hello,
I saw you have added support for reading global config file in 1ef8d19023c7c8f3c2c70c76cb7cd7215571f56f.
What I'm trying to do is making a custom `/etc/chromium-flags.conf` file and have it installed in equivalent path on the system when the package is being installed.
Assuming my `PKGBUILD` file is identical to `extra/chromium`'s one, what should I do?
Thanks.
